---
title: "Excersise 1_Markup_Christoph"
author: "Christoph Völtzke"
date: "2022-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(future)
library(furrr)
library(dplyr)
library(magrittr)
```
```{r}
nsim = 100
plan(multisession)
# start future mapping
SIM <- future_map(1:nsim, function(x){
  x <- rnorm(5000, mean = 0, sd = 1)
  M <- mean(x)
  DF <- length(x) - 1
  SE <- 1 / sqrt(length(x))
  INT <- qt(.975, DF) * SE
  return(c(mean = M, 
           bias = M - 0, 
           std.err = SE, 
           lower = M - INT, 
           upper = M + INT, 
           cov = M - INT < 0 & 0 < M + INT))
}, 
.options = furrr_options(seed = 123), 
.progress = TRUE) %>% 
  do.call("rbind", args = .) %>% 
  as_tibble
```

```{r}
SIM %>% colMeans
```

```{r}
SIM %>% filter(!cov)
```

```{r}
library(DT)
SIM %>% 
  round(4) %>% 
  datatable()
```

```{r}
library(ggplot2)
limits <- aes(ymax = SIM$upper, ymin = SIM$lower)
SIM %>% mutate(covered = as.factor(cov)) %>% 
ggplot(aes(y=mean, x=1:100, colour = covered)) + 
  geom_hline(aes(yintercept = 0), color = "dark grey", size = 2) + 
  geom_pointrange(limits) + 
  xlab("Simulations 1-100") +
  ylab("Means and 95% Confidence Intervals")
```









